server:
  port: 8080
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: mikooosia005@gmail.com
    password: ootgdxkfvsdctklf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
  application:
    name: "wehack-backend"
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME} # URL подключения к базе данных
    username: ${DB_USERNAME} # Имя пользователя для подключения к базе данных
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
  flyway:
    enabled: true # Включение Flyway для миграций базы данных
    baseline-on-migrate: true # Установка базовой версии при миграции
    locations: classpath:db/migration # Путь к файлам миграций
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME} # URL подключения к базе данных для Flyway
    user: ${DB_USERNAME:postgres} # Имя пользователя для подключения к базе данных для Flyway
    password: ${DB_PASSWORD:postgres} # Пароль для подключения к базе данных для Flyway
    schemas: ${DB_SCHEMAS:public} # Схемы базы данных, которые должны быть мигрированы
jwt:
  secret: ${JWT_SECRET_KEY:DHAZ7XLxWihFWk194JWLMHRxBh29Q22FTf7Ss9Slz0zwUSdJBmyA2OaCSTcGCmxroReFVCCkc99ViokJejocVVLWDArUUdZHiu0xxPqkJobsOGfh03529rryKJv8cdvvSkziZcfww776wKqkbDT2HxkPvCfILVWwXTYFqEefjoTPW2mlGwp1xI67IdCyw4atGxljop2pih0WAqesxcPqLHcxJSECTCUIKacOlmlpGSWohcQVHWHSpgvep0tJZBfr}
telegram:
  bots:
    bot-username: ${TG_BOT_NAME:sxodim_sdu_bot}
    bot-token: ${TG_BOT_TOKEN:7205732698:AAEyweTPXKQq8N--76PyNoeu4DLRFk2ozo4}
springdoc:
  api-docs:
    path: /v3/api-docs

stripe:
  public:
    key: ${STRIPE_PUBLIC_KEY:pk_test_51RKj6l2c4vLBscRz3OjblZz98uC6FXJPhttuJzaEGJoKYEp0J5C2IBD7bzn1yur8hIt4X6KPOtKN9yM44wkCqQZ8007iXq8DcI}
  secret:
    key: ${STRIPE_SECRET_KEY:sk_test_51RKj6l2c4vLBscRzH8uNAWbFnSqJ0pyObmo1X3SM7DfvUgDY3SxcDinozQBd2aNrcqrqjdIWUxTN7Y4fgJ7yyv2500guJa9mkX}
  webhook:
    secret: ${STRIPE_WEBHOOK_SECRET:whsec_3347fe9d7a6737a33b655e23c77f386ce19d91771a3baa376cbcd539eb428050}
    endpoint:
      url: ${STRIPE_WEBHOOK_URL:http://localhost:8080/api/payment/stripe-webhook}