server:
  port: 8080
spring:
  application:
    name: "wehack-backend"
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/wehack_db} # URL подключения к базе данных
    username: ${DB_USERNAME:postgres} # Имя пользователя для подключения к базе данных
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true # Включение Flyway для миграций базы данных
    baseline-on-migrate: true # Установка базовой версии при миграции
    locations: classpath:db/migration # Путь к файлам миграций
    url: ${DB_URL:jdbc:postgresql://localhost:5432/wehack_db} # URL подключения к базе данных для Flyway
    user: ${DB_USERNAME:postgres} # Имя пользователя для подключения к базе данных для Flyway
    password: ${DB_PASSWORD:postgres} # Пароль для подключения к базе данных для Flyway
    schemas: ${DB_SCHEMAS:public} # Схемы базы данных, которые должны быть мигрированы